up

diff --git a/prep-workshop/check b/prep-workshop/check
--- a/prep-workshop/check
+++ b/prep-workshop/check
@@ -2,20 +2,20 @@ echo "Checking workshop setup ..."
 TOKEN=$(curl -s --request PUT "http://169.254.169.254/latest/api/token" --header "X-aws-ec2-metadata-token-ttl-seconds: 3600")
 instid=$(curl -s http://169.254.169.254/latest/meta-data/instance-id --header "X-aws-ec2-metadata-token: $TOKEN")
 iname=$(aws ec2 describe-tags --filters "Name=resource-type,Values=instance" "Name=resource-id,Values=$instid" | jq -r '.Tags[] | select(.Key=="Name").Value')
-echo $iname| grep 'eks-workshop\|-Project-mod-' -q && echo "PASSED: Cloud9 IDE name is valid " || echo "ERROR: Cloud9 IDE name invalid! - DO NOT PROCEED"
+echo $iname | grep 'eks-workshop\|-Project-mod-' -q && echo "PASSED: Cloud9 IDE name is valid " || echo "ERROR: Cloud9 IDE name invalid! - DO NOT PROCEED"
 #echo $instid
-aws sts get-caller-identity --query Arn | grep eksworkshop-admin -q && echo "PASSED: IAM role valid" || (echo "ERROR: IAM role not valid - DO NOT PROCEED"  && echo "Check Cloud9 AWS Managed temporary credentials are disabled - in AWS Settings")
-ip=`aws ec2 describe-iam-instance-profile-associations --filters "Name=instance-id,Values=$instid" | jq .IamInstanceProfileAssociations[0].IamInstanceProfile.Arn | rev | cut -f1 -d'/' | rev | tr -d '"'`
+aws sts get-caller-identity --query Arn | grep eksworkshop-admin -q && echo "PASSED: IAM role valid" || (echo "ERROR: IAM role not valid - DO NOT PROCEED" && echo "Check Cloud9 AWS Managed temporary credentials are disabled - in AWS Settings")
+ip=$(aws ec2 describe-iam-instance-profile-associations --filters "Name=instance-id,Values=$instid" | jq .IamInstanceProfileAssociations[0].IamInstanceProfile.Arn | rev | cut -f1 -d'/' | rev | tr -d '"')
 #echo "Instance Profile=$ip"
-if [ "$ip" != "eksworkshop-admin" ] ; then
-echo "ERROR: Could not find Instance profile eksworkshop-admin - DO NOT PROCEED"
-exit
+if [ "$ip" != "eksworkshop-admin" ]; then
+    echo "ERROR: Could not find Instance profile eksworkshop-admin - DO NOT PROCEED"
+    exit
 else
-echo "PASSED: Found Instance profile $ip - proceed with the workshop"
+    echo "PASSED: Found Instance profile $ip"
 fi
 if [[ -z "${TF_VAR_awsalias}" ]]; then
     echo "ERROR: TF_VAR_awsalias needs to be set to your AWS hosts alais - please discuss with workshop host"
     echo "export TF_VAR_awsalias=<host alias>"
+else
+    echo "PASSED: Found Instance profile $TF_VAR_awsalias - proceed with the workshop"
 fi
-
-
