up

diff --git a/setup b/setup
--- a/setup
+++ b/setup
@@ -106,6 +106,45 @@ python3 get-pip.py 2 &>/dev/null
 echo "git-remote-codecommit"
 pip3 install git-remote-codecommit 2 &>/dev/null
 
+
+this=$(pwd)
+#echo "sample apps"
+cd ~/environment
+
+echo "Enable bash_completion"
+. /etc/profile.d/bash_completion.sh &>/dev/null
+. ~/.bash_completion
+echo "alias tfb='terraform init && terraform plan -out tfplan && terraform apply tfplan'" >>~/.bash_profile
+echo "alias aws='/usr/local/bin/aws'" >>~/.bash_profile
+source ~/.bash_profile
+#
+test -n "$AWS_REGION" && echo "PASSED: AWS_REGION is $AWS_REGION" || echo AWS_REGION is not set !!
+test -n "$TF_VAR_region" && echo "PASSED: TF_VAR_region is $TF_VAR_region" || echo TF_VAR_region is not set !!
+test -n "$ACCOUNT_ID" && echo "PASSED: ACCOUNT_ID is $ACCOUNT_ID" || echo ACCOUNT_ID is not set !!
+echo "setup tools run" >>~/setup-tools.log
+cd ~/environment/tfekscode/lb2
+#curl -o iam-policy.json https://raw.githubusercontent.com/kubernetes-sigs/aws-load-balancer-controller/main/docs/install/iam_policy.json -s
+curl --silent -o iam_policy.json https://raw.githubusercontent.com/kubernetes-sigs/aws-load-balancer-controller/v2.5.0/docs/install/iam_policy.json
+cd $this
+if [[ ! -z $C9_PID ]];then
+  profile_name="eksworkshop-admin"
+  instance_id=$(curl -sS http://169.254.169.254/latest/meta-data/instance-id)
+  ipa=$(aws ec2 describe-instances --instance-ids $instance_id --query Reservations[].Instances[].IamInstanceProfile | jq -r .[].Arn)
+  iip=$(aws ec2 describe-iam-instance-profile-associations --filters "Name=instance-id,Values=$instance_id" --query IamInstanceProfileAssociations[].AssociationId | jq -r .[])
+  echo "Associate $profile_name"
+  if aws ec2 replace-iam-instance-profile-association --iam-instance-profile "Name=$profile_name" --association-id $iip; then
+    if aws cloud9 update-environment --environment-id $C9_PID --managed-credentials-action DISABLE 2>/dev/null; then
+      rm -vf ${HOME}/.aws/credentials
+      echo "Profile eksworkshop-admin associated successfully."
+    fi
+  else
+    echo "ERROR: Encountered error associating instance profile eksworkshop-admin with Cloud9 environment"
+  fi
+fi
+
+
+# Having switched instance profile do disks......
+#
 # ------  resize OS disk -----------
 # Specify the desired volume size in GiB as a command-line argument. If not specified, default to 32 GiB.
 VOLUME_SIZE=${1:-32}
@@ -151,44 +190,6 @@ df -m /
 #
 #
 
-
-this=$(pwd)
-#echo "sample apps"
-cd ~/environment
-
-echo "Enable bash_completion"
-. /etc/profile.d/bash_completion.sh &>/dev/null
-. ~/.bash_completion
-echo "alias tfb='terraform init && terraform plan -out tfplan && terraform apply tfplan'" >>~/.bash_profile
-echo "alias aws='/usr/local/bin/aws'" >>~/.bash_profile
-source ~/.bash_profile
-#
-test -n "$AWS_REGION" && echo "PASSED: AWS_REGION is $AWS_REGION" || echo AWS_REGION is not set !!
-test -n "$TF_VAR_region" && echo "PASSED: TF_VAR_region is $TF_VAR_region" || echo TF_VAR_region is not set !!
-test -n "$ACCOUNT_ID" && echo "PASSED: ACCOUNT_ID is $ACCOUNT_ID" || echo ACCOUNT_ID is not set !!
-echo "setup tools run" >>~/setup-tools.log
-cd ~/environment/tfekscode/lb2
-#curl -o iam-policy.json https://raw.githubusercontent.com/kubernetes-sigs/aws-load-balancer-controller/main/docs/install/iam_policy.json -s
-curl --silent -o iam_policy.json https://raw.githubusercontent.com/kubernetes-sigs/aws-load-balancer-controller/v2.5.0/docs/install/iam_policy.json
-cd $this
-if [[ ! -z $C9_PID ]];then
-  profile_name="eksworkshop-admin"
-  instance_id=$(curl -sS http://169.254.169.254/latest/meta-data/instance-id)
-  ipa=$(aws ec2 describe-instances --instance-ids $instance_id --query Reservations[].Instances[].IamInstanceProfile | jq -r .[].Arn)
-  iip=$(aws ec2 describe-iam-instance-profile-associations --filters "Name=instance-id,Values=$instance_id" --query IamInstanceProfileAssociations[].AssociationId | jq -r .[])
-  echo "Associate $profile_name"
-  if aws ec2 replace-iam-instance-profile-association --iam-instance-profile "Name=$profile_name" --association-id $iip; then
-    if aws cloud9 update-environment --environment-id $C9_PID --managed-credentials-action DISABLE 2>/dev/null; then
-      rm -vf ${HOME}/.aws/credentials
-      echo "Profile eksworkshop-admin associated successfully."
-    fi
-  else
-    echo "ERROR: Encountered error associating instance profile eksworkshop-admin with Cloud9 environment"
-  fi
-fi
-#
-echo "For final checks - run ./check"
-#
 # setup for eksworkshop.com
 #
 sudo mv ~/environment/tfekscode/.eks-workshop-support/reset-environment /usr/local/bin/reset-environment >/dev/null
